networks:
  global-processing:
    driver: bridge
    name: global-processing

configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_federation, rabbitmq_federation_management, rabbitmq_shovel, rabbitmq_shovel_management]."

services:
  rabbitmq-global:
    build:
      context: ./rabbitmq-global
      dockerfile: Dockerfile
    container_name: rabbitmq-global
    image: rabbitmq-global
    ports:
      - 15673:15672
      - 5673:5672
    networks:
      - global-processing
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    env_file:
      - .env

  global-processing-engine:
    build:
      context: ./global-processing-engine
      dockerfile: Dockerfile
    container_name: global-processing
    image: global-processing-engine
    networks:
      - global-processing
    depends_on:
      rabbitmq-global:
        condition: service_healthy
    env_file:
      - .env
